name: Prerelease

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get next Version
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches : .*
        dry_run: true

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Build jar with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}-SNAPSHOT' jar

    - name: Publish to GitHub Maven with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}-SNAPSHOT' publishInterlisCustomFunctionsPublicationToGitHubPackagesRepository
      env:
        ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
        ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    - name: Publish to OSSRH Maven with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}-SNAPSHOT' publishToSonatype
      env:
        ORG_GRADLE_PROJECT_OSSRH_USER: ${{ secrets.OSSRH_USER }}
        ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
      with:
        artifacts: "build/libs/*.jar"
        allowUpdates: true
        name: ${{ steps.tag_version.outputs.new_tag }}-SNAPSHOT
        tag: ${{ steps.tag_version.outputs.new_tag }}-SNAPSHOT-${{ github.run_id }}
        commit: ${{ github.sha }}
        body: ${{ steps.tag_version.outputs.changelog }}
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
