name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: .*

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Build jar with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}' jar

    - name: Publish to GitHub Maven with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}' publishInterlisCustomFunctionsPublicationToGitHubPackagesRepository
      env:
        ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
        ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
      with:
        artifacts: "build/libs/*.jar"
        makeLatest: true
        name: ${{ steps.tag_version.outputs.new_tag }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        token: ${{ secrets.GITHUB_TOKEN }}
